server:
  port: 8888

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/pait
    driver-class-name: com.mysql.jdbc.Driver
  redis:
          host: 127.0.0.1
          port: 6379
          password: #password#
          timeout: 2000
          pool:
              max-active: 8
              max-wait: -1
              max-idle: 8
              min-idle: 0
  session:
      store-type: redis
      redis:
          namespace: jkg

shiro:
    enabled: false

mybatis:
    mapper-locations: classpath:mybatis/*.xml
mapper:
    mappers: com.mloine.auth.auths.entity.base.CommonMapper
pagehelper:
    reasonable: true

